version: '3.5'

services:
  database:
    container_name: bookstore-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bookstore
      POSTGRES_PASSWORD: bookstore
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
  eureka:
    container_name: bookstore-eureka
    build:
      dockerfile: DiscoveryService/Dockerfile
  config:
    container_name: bookstore-config
    build:
      dockerfile: ConfigurationService/Dockerfile
    volumes:
      - ./configuration:/opt/config
  userService:
    container_name: userService
    build:
      dockerfile: UserService/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - database
      - eureka
      - config
    environment:
      SERVER_PORT: 8081
  bookstore:
    container_name: bookstore
    build:
      dockerfile: BookstoreService/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
      - eureka
      - userService
      - config
    environment:
      SERVER_PORT: 8080
