version: '3.5'

services:
  database:
    container_name: bookstore-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bookstore
      POSTGRES_PASSWORD: bookstore
      POSTGRES_MULTIPLE_DATABASES: "bookslease,bookstore: userservice,bookstore"
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
      - ./.postgres-init:/docker-entrypoint-initdb.d
  eureka:
    container_name: bookstore-eureka
    image: bookstore-eureka
    build:
      context: DiscoveryService/
      dockerfile: ../Dockerfile
    ports:
      - "8761:8761"
  config:
    container_name: bookstore-config
    image: bookstore-config
    build:
      context: ConfigurationService/
      dockerfile: ../Dockerfile
    depends_on:
      - eureka
    ports:
        - "8888:8888"
    restart: on-failure
    volumes:
      - ./configuration:/opt/config
  userService:
    container_name: bookstore-user-service
    image: bookstore-user-service
    build:
      context: UserService/
      dockerfile: ../Dockerfile
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - database
      - eureka
      - config
    environment:
      SERVER_PORT: 8081
  bookstore:
    container_name: bookstore-bookstore-service
    image: bookstore-bookstore-service
    build:
      context: BookStoreService/
      dockerfile: ../Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - database
      - eureka
      - userService
      - config
      - library
    environment:
      SERVER_PORT: 8080
  gateway:
    container_name: bookstore-gateway-service
    image: bookstore-gateway-service
    build:
      context: GatewayService/
      dockerfile: ../Dockerfile
    ports:
      - "8083:8083"
    restart: on-failure
    depends_on:
      - eureka
      - config
    environment:
      SERVER_PORT: 8083
  library:
    container_name: bookstore-library-service
    image: bookstore-library-service
    build:
      context: LibraryService/
      dockerfile: ../Dockerfile
    ports:
      - "8082:8082"
    restart: on-failure
    depends_on:
      - database
      - eureka
      - userService
      - config
    environment:
      SERVER_PORT: 8082
