eureka:
  client:
    webclient:
      enabled: true
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: lb://userService
          predicates:
            - Path=/users/{segment1},/users/{segment1}/{segment2}
          filters:
            - JwtFilter
        - id: users-login
          uri: lb://userService
          predicates:
            - Path=/auth/login
        - id: users-create
          uri: lb://userService
          predicates:
            - Path=/users
            - Method=PUT
        - id: bookstore
          uri: lb://bookstore
          predicates:
            - Path=/books/**,/books,/authors/**,/authors,/book/**,/book
          filters:
            - JwtFilter
        - id: library
          uri: lb://library
          predicates:
            - Path=/books-lease/**
          filters:
            - JwtFilter